teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
      z: 5
    scale_linear:
      x: -0.5
      z: -0.5

    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 0.5

    require_enable_button: false

  # ros2 launch teleop_twist_joy teleop-launch.py config_filepath:='/home/pi/ros2_ws/src/wheeled_biped_controller/config/teleop.config.yaml'